# Artifivial Neural Network - 140623)

## Part I - Data Preprocessing

### 1. Importing the libraries

In [1]:
#kalau belum di instal
#!pip install tensorflow

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

### 2. Importing the dataset

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [4]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [5]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

### 3. Encoding Categorical Data

#### Label Encoding Gender Column

hanya bisa digunakan untuk 2 jenis saja, seperti gender yaitu female dan male, maka baru bisa menggunakan laber encoder, namun untuk lebih dari 2 tidak bisa

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [7]:
X
#female = 0
#male = 1

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [8]:
# untuk geography column
#from sklearn.preprocessing import LabelEncoder
#le = LabelEncoder()
#X[:,1] = le.fit_transform(X[:,1])

In [9]:
#X
# france = 0
#Germany = 1
#Spain = 2

#### One Hot Encoding for Geography Column
alternatif lain untuk lebih dari 2 jenis

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))
X

# france = 1.0, 0.0, 0.0
#Germany = 0.0, 1.0, 0.0
#Spain = 0.0, 0.0, 1.0

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

### 4. Splitting the Dataset into Training Set and Test Set

In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [26]:
X_test

array([[0.0, 1.0, 0.0, ..., 1, 1, 192852.67],
       [1.0, 0.0, 0.0, ..., 1, 0, 128702.1],
       [0.0, 0.0, 1.0, ..., 1, 1, 75732.25],
       ...,
       [0.0, 0.0, 1.0, ..., 1, 0, 141533.19],
       [0.0, 1.0, 0.0, ..., 1, 1, 11276.48],
       [0.0, 1.0, 0.0, ..., 1, 0, 192950.6]], dtype=object)

In [27]:
y_test

array([0, 1, 0, ..., 0, 0, 0], dtype=int64)

In [33]:
#baris 5 semua kolom
X_test[5,:]

array([0.0, 0.0, 1.0, 670, 0, 57, 3, 175575.95, 2, 1, 0, 99061.75],
      dtype=object)

In [32]:
#baris 5
y_test[5]

1

### 5. Feature Scalling

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building ANN

### 1. Initializing the ANN

In [13]:
ann = tf.keras.models.Sequential()

### 2. Adding input layer and the first hidden layer

In [14]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### 3. Adding Second Layer

In [15]:
ann.add(tf.keras.layers.Dense(units = 6, activation = 'relu'))

### 4. Output Layers

In [16]:
ann.add(tf.keras.layers.Dense(units = 1, activation = 'sigmoid'))

## Part 3 - Training ANN

### 1. Compiling the ANN

In [17]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'] )

### 2. Training the ANN on the Training Set

In [18]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.7617 - accuracy: 0.5159
Epoch 2/100
250/250 [==============================] - 0s 887us/step - loss: 0.5026 - accuracy: 0.7961
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4670 - accuracy: 0.7981
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4489 - accuracy: 0.8030
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4382 - accuracy: 0.8055
Epoch 6/100
250/250 [==============================] - 0s 804us/step - loss: 0.4315 - accuracy: 0.8101
Epoch 7/100
250/250 [==============================] - 0s 772us/step - loss: 0.4268 - accuracy: 0.8148
Epoch 8/100
250/250 [==============================] - 0s 756us/step - loss: 0.4231 - accuracy: 0.8205
Epoch 9/100
250/250 [==============================] - 0s 953us/step - loss: 0.4201 - accuracy: 0.8226
Epoch 10/100
250/250 [==============================] - 0s 756us/step - loss: 0.4

### 3. Predicting the Test Set Results

In [19]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 947us/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### 4. Making a Confussion Matriks

In [20]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1505   90]
 [ 192  213]]


### 5. Accuracy Score

In [21]:
accuracy_score(y_test, y_pred)

0.859

### 6. Making a Single Prediction

Use our ANN model to predict if the customer with the following informations will leave the bank:

Geography : France

Credit Score : 600

Gender : Male

Age : 40 Years Old

Tenure : 3 Years

Balance : $60000

Number of Products : 2

Does this customer have a credit card ? yes

is this customer an Active Member : yes

Estimated Salary : $50000

So, should we say goodbye to that customer?



In [22]:
ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 5000]]))

1/1 [==============================] - 0s 26ms/step


array([[0.02324675]], dtype=float32)

In [30]:
ann.predict(sc.transform([[1.0, 0.0, 0.0, 523, 0, 40, 2, 102967.41, 1, 1, 0, 128702.1]])) > 0.5

#false artinya tidak keluar ttp jadi nasabah

1/1 [==============================] - 0s 17ms/step


array([[False]])