In [1]:
import pandas as pd
import numpy as np


In [2]:
dataset = np.array([[7000,45],[6000,44],[52000,40]])
dataset

array([[ 7000,    45],
       [ 6000,    44],
       [52000,    40]])

In [4]:
# Normalisasi (min, max)
from sklearn.preprocessing import MinMaxScaler
sclaer = MinMaxScaler ()

In [5]:
#fit transform pada datset
dataset_sc = sclaer.fit_transform(dataset)
dataset_sc

array([[0.02173913, 1.        ],
       [0.        , 0.8       ],
       [1.        , 0.        ]])

In [9]:
# Standarisasi
from sklearn.preprocessing import StandardScaler
scaler2 = StandardScaler()

In [10]:
std_dataset =  scaler2.fit_transform(dataset)
std_dataset

array([[-0.68367174,  0.9258201 ],
       [-0.73028572,  0.46291005],
       [ 1.41395746, -1.38873015]])

# Split Dataset

In [14]:
# Matriks awal
matriks_awal = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
matriks_awal

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
from sklearn.model_selection import train_test_split
train_set, test_set = train_test_split(matriks_awal, test_size=0.2, random_state=1)
print('Traning Set:')
print(train_set)
print('Test Set:')
print(test_set)

Traning Set:
[[7 8 9]
 [4 5 6]]
Test Set:
[[1 2 3]]
