In [1]:
import numpy as np

In [2]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
#0D Array
arr = np.array(42)
print(arr)

42


In [ ]:
#2D Array
arr = np.array ([ [1,2,3,4,5] , [6,7,8,9,10] ])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
#3D Array
arr = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])
print(arr)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


In [ ]:
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([ [1,2,3,4,5],[6,7,8,9,10] ])
d = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
arr =  np.array([1,2,3,4])
print(arr[0])

1


In [ ]:
arr =  np.array([1,2,3,4])
print(arr[2]+arr[3])

7


In [ ]:
arr = np.array([ [1,2,3,4,5],[6,7,8,9,10] ])
print('2nd element on 1st row: ', arr[0,1])

2nd element on 1st row:  2


In [ ]:
arr = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])
print(arr[0,1,2])

8


In [ ]:
arr = np.array([ [1,2,3,4,5],[6,7,8,9,10] ])
print('Last element from 2nd dim: ', arr[1,-1])

Last element from 2nd dim:  10


In [ ]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [ ]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[:4])

[1 2 3 4]


In [ ]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[4:])

[5 6 7]


In [ ]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])

[5 6]


In [ ]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])

[2 4]


In [ ]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]


In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1, 1:4])

[7 8 9]


In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2, 2])

[3 8]


In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2 ,  1:4])

[[2 3 4]
 [7 8 9]]


In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr.shape)

(2, 5)


In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9])
newarr= arr.reshape(3,3)
print(newarr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
arr = np.array([1,2,3,4,5,6,7,8])
newarr = arr.reshape(2,2,-1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6 7 8]


In [ ]:
arr = np.array([1,2,3])

for x in arr:
    print(x)

1
2
3


In [9]:
arr = np.array ([1,2,3,4,5,6])
newarr = arr.reshape(3,2)

for x in arr:
    for i in newarr:
        print(i)


[1 2]
[3 4]
[5 6]
[1 2]
[3 4]
[5 6]
[1 2]
[3 4]
[5 6]
[1 2]
[3 4]
[5 6]
[1 2]
[3 4]
[5 6]
[1 2]
[3 4]
[5 6]


In [11]:
arr = np.array([[1,2,3,4],[5,6,7,8]])

for i in arr:
    print(i)

[1 2 3 4]
[5 6 7 8]


In [12]:
arr = np.array([[1,2,3,4],[5,6,7,8]])

for x in arr:
    for i in x:
        print(i)

1
2
3
4
5
6
7
8


In [14]:
arr = np.array([[[1,2,3,4],[5,6,7,8]],[[5,6,7,8],[9,10,11,12]]])
for x in arr:
    print(x)

[[1 2 3 4]
 [5 6 7 8]]
[[ 5  6  7  8]
 [ 9 10 11 12]]


In [17]:
arr = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]]])

for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [18]:
arr = np.array ([[[1,2],[3,4]],[[5,6],[7,8]]])
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [19]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [20]:
arr = np.array([1,2,3,4,5,6])
newarr = np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [21]:
arr = np.array([1,2,3,4,5,4,4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6], dtype=int64),)


In [23]:
arr = np.array ([3,2,0,1])
print(np.sort(arr))

[0 1 2 3]


In [24]:

arr = np.array([41,42,43,44])
x  = [True,False,True,False]
newarr = arr[x]
print(newarr)

[41 43]


In [25]:
arr =  np.array([41,42,43,44])

filter_arr = []

for element in arr:
    if element > 42 :
        filter_arr.append(True)
    else :
        filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]
