In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'matplotlib'

In [ ]:
df = pd.read_csv('drug200.csv')
df.head

<bound method NDFrame.head of      Age Sex      BP Cholesterol  Na_to_K   Drug
0     23   F    HIGH        HIGH   25.355  DrugY
1     47   M     LOW        HIGH   13.093  drugC
2     47   M     LOW        HIGH   10.114  drugC
3     28   F  NORMAL        HIGH    7.798  drugX
4     61   F     LOW        HIGH   18.043  DrugY
..   ...  ..     ...         ...      ...    ...
195   56   F     LOW        HIGH   11.567  drugC
196   16   M     LOW        HIGH   12.006  drugC
197   52   M  NORMAL        HIGH    9.894  drugX
198   23   M  NORMAL      NORMAL   14.020  drugX
199   40   F     LOW      NORMAL   11.349  drugX

[200 rows x 6 columns]>

In [ ]:
df.shape

(200, 6)

In [ ]:
df['Sex'].value_counts()

M    104
F     96
Name: Sex, dtype: int64

In [ ]:
# Merubah String menjadi INT dengan Label Encoder
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
df['Sex'] = label_encoder.fit_transform(df['Sex'])
df['Sex'].unique()

array([0, 1])

In [ ]:
# Merubah String menjadi INT dengan Fungsi Encode
def encode(df):
  if df == 'LOW':
    return 0
  elif df == 'NORMAL':
    return 1
  else : 
    return 2

df['BP'] = df['BP'].apply(encode)

In [ ]:
df['Cholesterol'].value_counts()

HIGH      103
NORMAL     97
Name: Cholesterol, dtype: int64

In [ ]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
df['Cholesterol'] = label_encoder.fit_transform(df['Cholesterol'])
df['Cholesterol'].unique()

array([0, 1])

In [ ]:
X = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [ ]:
X

array([[23.   ,  0.   ,  2.   ,  0.   , 25.355],
       [47.   ,  1.   ,  0.   ,  0.   , 13.093],
       [47.   ,  1.   ,  0.   ,  0.   , 10.114],
       [28.   ,  0.   ,  1.   ,  0.   ,  7.798],
       [61.   ,  0.   ,  0.   ,  0.   , 18.043],
       [22.   ,  0.   ,  1.   ,  0.   ,  8.607],
       [49.   ,  0.   ,  1.   ,  0.   , 16.275],
       [41.   ,  1.   ,  0.   ,  0.   , 11.037],
       [60.   ,  1.   ,  1.   ,  0.   , 15.171],
       [43.   ,  1.   ,  0.   ,  1.   , 19.368],
       [47.   ,  0.   ,  0.   ,  0.   , 11.767],
       [34.   ,  0.   ,  2.   ,  1.   , 19.199],
       [43.   ,  1.   ,  0.   ,  0.   , 15.376],
       [74.   ,  0.   ,  0.   ,  0.   , 20.942],
       [50.   ,  0.   ,  1.   ,  0.   , 12.703],
       [16.   ,  0.   ,  2.   ,  1.   , 15.516],
       [69.   ,  1.   ,  0.   ,  1.   , 11.455],
       [43.   ,  1.   ,  2.   ,  0.   , 13.972],
       [23.   ,  1.   ,  0.   ,  0.   ,  7.298],
       [32.   ,  0.   ,  2.   ,  1.   , 25.974],
       [57.   ,  1. 

In [ ]:
y

array(['DrugY', 'drugC', 'drugC', 'drugX', 'DrugY', 'drugX', 'DrugY',
       'drugC', 'DrugY', 'DrugY', 'drugC', 'DrugY', 'DrugY', 'DrugY',
       'drugX', 'DrugY', 'drugX', 'drugA', 'drugC', 'DrugY', 'DrugY',
       'DrugY', 'DrugY', 'DrugY', 'DrugY', 'DrugY', 'DrugY', 'drugX',
       'DrugY', 'DrugY', 'drugX', 'drugB', 'drugX', 'DrugY', 'drugX',
       'drugX', 'drugA', 'drugX', 'drugX', 'drugX', 'DrugY', 'drugB',
       'DrugY', 'drugX', 'drugX', 'drugX', 'drugA', 'drugC', 'DrugY',
       'DrugY', 'DrugY', 'drugX', 'DrugY', 'DrugY', 'drugB', 'drugC',
       'drugB', 'DrugY', 'drugX', 'DrugY', 'DrugY', 'drugA', 'DrugY',
       'drugX', 'drugB', 'DrugY', 'drugA', 'drugX', 'DrugY', 'DrugY',
       'drugB', 'DrugY', 'drugX', 'DrugY', 'DrugY', 'DrugY', 'drugA',
       'DrugY', 'drugA', 'drugX', 'drugB', 'drugX', 'drugC', 'drugA',
       'drugC', 'drugB', 'drugX', 'DrugY', 'DrugY', 'DrugY', 'DrugY',
       'DrugY', 'DrugY', 'DrugY', 'DrugY', 'drugX', 'DrugY', 'DrugY',
       'DrugY', 'Dru

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=0)

In [ ]:
X_test

array([[23.   ,  1.   ,  0.   ,  0.   ,  7.298],
       [28.   ,  0.   ,  1.   ,  0.   , 12.879],
       [42.   ,  1.   ,  0.   ,  0.   , 20.013],
       [20.   ,  1.   ,  2.   ,  1.   , 35.639],
       [25.   ,  1.   ,  1.   ,  0.   , 19.011],
       [20.   ,  0.   ,  0.   ,  1.   , 11.686],
       [22.   ,  0.   ,  1.   ,  0.   ,  8.607],
       [37.   ,  0.   ,  0.   ,  1.   , 12.006],
       [43.   ,  1.   ,  0.   ,  0.   , 15.376],
       [55.   ,  1.   ,  1.   ,  1.   ,  7.261],
       [24.   ,  1.   ,  2.   ,  1.   ,  9.475],
       [19.   ,  0.   ,  2.   ,  1.   , 25.969],
       [22.   ,  0.   ,  2.   ,  1.   , 22.818],
       [37.   ,  1.   ,  0.   ,  1.   , 16.724],
       [60.   ,  1.   ,  2.   ,  0.   , 13.934],
       [41.   ,  1.   ,  0.   ,  0.   , 11.037],
       [65.   ,  0.   ,  2.   ,  1.   , 31.876],
       [70.   ,  0.   ,  1.   ,  0.   , 20.489],
       [39.   ,  1.   ,  0.   ,  1.   , 13.938],
       [31.   ,  1.   ,  2.   ,  1.   , 17.069],
       [36.   ,  0. 

In [ ]:
y_test

array(['drugC', 'drugX', 'DrugY', 'DrugY', 'DrugY', 'drugX', 'drugX',
       'drugX', 'DrugY', 'drugX', 'drugA', 'DrugY', 'DrugY', 'DrugY',
       'drugB', 'drugC', 'DrugY', 'DrugY', 'drugX', 'DrugY', 'DrugY',
       'drugX', 'drugX', 'drugX', 'DrugY', 'DrugY', 'DrugY', 'DrugY',
       'DrugY', 'drugX', 'drugX', 'drugC', 'drugA', 'drugX', 'DrugY',
       'DrugY', 'drugX', 'DrugY', 'drugA', 'drugX'], dtype=object)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test  = sc.fit_transform(X_test)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion='entropy', random_state=0)
classifier.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [ ]:
y_dc = classifier.predict(X_test)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
RandomForest = RandomForestClassifier(n_estimators=10,criterion='entropy', random_state=0)
RandomForest.fit(X_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [ ]:
y_rf = RandomForest.predict(X_test)

In [ ]:
from sklearn.svm import SVC
rbf = SVC(kernel = 'rbf', random_state = 0)
rbf.fit(X_train, y_train)

SVC(random_state=0)

In [ ]:
y_svm_rbf = rbf.predict(X_test)

In [ ]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(random_state=0)
lr.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [ ]:
y_lr = lr.predict(X_test)

In [ ]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train, y_train)

GaussianNB()

In [ ]:
y_pred_gnb = gnb.predict(X_test)

In [ ]:
from sklearn.svm import SVC
linear_svm = SVC(kernel= 'linear')
linear_svm.fit(X_train, y_train)

SVC(kernel='linear')

In [ ]:
y_pred_svm = linear_svm.predict(X_test)

# Acuracy Test

In [ ]:
# Dicision Tree
from sklearn.metrics import confusion_matrix, accuracy_score
accuracy_score(y_test, y_dc)

0.975

In [ ]:
# Random Forest
from sklearn.metrics import confusion_matrix, accuracy_score
accuracy_score(y_test, y_rf)

0.975

In [ ]:
# Random Forest
from sklearn.metrics import confusion_matrix, accuracy_score
accuracy_score(y_test, y_svm_rbf)

0.975

In [ ]:
# Random Forest
from sklearn.metrics import confusion_matrix, accuracy_score
accuracy_score(y_test, y_lr)

0.975